apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskai.fullname" . }}-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "taskai.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
      {{- if eq .Values.backend.service.type "NodePort" }}
      nodePort: {{ .Values.backend.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "taskai.backend.selectorLabels" . | nindent 4 }}
