apiVersion: v1
kind: Service
metadata:
  name: {{ include "taskai.fullname" . }}-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "taskai.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: 3000
      {{- if eq .Values.frontend.service.type "NodePort" }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      {{- end }}
      protocol: TCP
      name: http
  selector:
    {{- include "taskai.frontend.selectorLabels" . | nindent 4 }}
